spring:
  datasource:
    url: jdbc:mysql://localhost/2Bdone
    username: root
    password: Passw0rd!
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
      naming_strategy: org.hibernate.cfg.EJB3NamingStrategy

flyway:
  enabled: true
  out-of-order: true
  encoding: UTF-8

server:
  port: 8088
  address: localhost

---
spring:
    profiles: test
    datasource:
          url: jdbc:h2:mem:2Bdone;DB_CLOSE_DELAY=-1;MODE=MySQL;INIT=RUNSCRIPT FROM 'classpath:init_test_db.sql';
          username: root
          password:
          driver-class-name: org.h2.Driver

---
spring:
    profiles: production