CREATE TABLE `TASK` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(256) NOT NULL,
  `IS_COMPLETED` BIT NOT NULL,
  `TIME_CREATED` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;